name: Test and Deploy static content to Pages

on: 
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  Continuous-Integration:
    name: Login Tests
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          echo Instalação das dependências do Projeto
          pip install robotframework-seleniumlibrary

      - name: Run Robot Framework tests
        run: |
          echo Executando os testes de Login
          robot --name "Login Tests" --outputdir results/ tests 
      
      - name: Test Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: robot-framework-report-api
          path: results/
