name: Deploy static content to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  Continuos-Integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        run: |
          sudo apt-get update
          sudo apt install python3
          sudo apt install wget
          pip install robotframework
          pip install robotframework-seleniumlibrary
          pip install webdriver-manager
          sudo apt install google-chrome-stable

      - name: Install ChromeDriver using WebDriver Manager
        run: |
          python3 -m pip install webdriver-manager

      - name: Verify Chrome version
        run: |
          google-chrome --version
          chromedriver --version

      - name: Verify 
        run: |
          which chromedriver
          ls -l /usr/bin/chromedriver

      - name: Run Robot Framework Tests
        run: |
          # Cria um diretório temporário único para o Chrome
          export CHROME_USER_DATA_DIR=$(mktemp -d)
          echo "CHROME_USER_DATA_DIR=$CHROME_USER_DATA_DIR"  # Imprime para depuração
      #     # Executa o Robot Framework, passando a variável correta
      #     robot --variable CHROME_USER_DATA_DIR:${CHROME_USER_DATA_DIR} teste/login.robot || exit 1
