name: Deploy static content to Pages

on:
  workflow_run:
    workflows: [ci"]
    types:
      - completed
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    name: Deploy GitHub Pages 🌐
    runs-on: ubuntu-24.04
    needs: 
      - merge
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: https://horadoqa.github.io/ci-cd-robot-framework/site/
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with: 
          name: robot-framework-report

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./site/

      - name: Deploy to Github Pages
        id: deployment
        uses: actions/deploy-pages@v4



        

