name: Robot Framework Tests

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

concurrency:
  group: "test"
  cancel-in-progress: false

jobs:
  test_web:
    name: Login Tests
    runs-on: ubuntu-latest
    needs: deploy  # Garante que o deploy esteja completo antes de rodar os testes

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          echo Instalação das dependências do Projeto
          pip install robotframework
          pip install robotframework-seleniumlibrary

      - name: Run Robot Framework tests
        run: |
          echo Executando os testes de Login
          robot --name "Login Tests" --outputdir results/ tests/login/
